version: "3.8"

services:
  # ----------------------------------------------------
  # Consul
  # ----------------------------------------------------
  consul:
    image: consul:1.15
    container_name: consul
    platform: linux/amd64
    restart: on-failure
    ports:
      - "8500:8500"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 10s
      retries: 5

  # ----------------------------------------------------
  # Config Server
  # ----------------------------------------------------
  config-server:
      image: docker.io/boughroudi/config-server:latest
      container_name: config-server
      platform: linux/amd64
      restart: on-failure
      ports:
        - "8888:8888"
      networks:
        - my-network
      depends_on:
        - consul
      healthcheck:
        test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
        interval: 10s
        timeout: 17s
        retries: 10

  # ----------------------------------------------------
  # RabbitMQ
  # ----------------------------------------------------
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------
  # MongoDB (for kidney-stone-service)
  # ----------------------------------------------------
  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    platform: linux/amd64
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - my-network

  # ----------------------------------------------------
  # Patient Management Service
  # ----------------------------------------------------
  patient-management-service:
      image: docker.io/boughroudi/patient-management-service:latest
      container_name: patient-management-service
      platform: linux/amd64
      restart: on-failure
      ports:
        - "8082:8080"
      depends_on:
        - config-server
        - consul
      networks:
        - my-network
  #  # ----------------------------------------------------
  #  # Consul Configuration Loader
  #  # ----------------------------------------------------
  consul-config-loader:
    image: curlimages/curl:latest
    container_name: consul-config-loader
    restart: on-failure
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - my-network
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - >
        set -x;
        echo "Waiting for Consul...";
        sleep 5;
        echo "Loading configuration into Consul KV Store...";
        curl --request PUT --data "jdbc:h2:mem:billingdb" http://consul:8500/v1/kv/config/billing-service/spring.datasource.url;
        curl --request PUT --data "org.h2.Driver" http://consul:8500/v1/kv/config/billing-service/spring.datasource.driver-class-name;
        curl --request PUT --data "sa" http://consul:8500/v1/kv/config/billing-service/spring.datasource.username;
        curl --request PUT --data "" http://consul:8500/v1/kv/config/billing-service/spring.datasource.password;
        curl --request PUT --data "org.hibernate.dialect.H2Dialect" http://consul:8500/v1/kv/config/billing-service/spring.jpa.database-platform;
        curl --request PUT --data "create-drop" http://consul:8500/v1/kv/config/billing-service/spring.jpa.hibernate.ddl-auto;
        curl --request PUT --data "true" http://consul:8500/v1/kv/config/billing-service/spring.jpa.show-sql;
        curl --request PUT --data "rabbitmq" http://consul:8500/v1/kv/config/billing-service/spring.rabbitmq.host;
        curl --request PUT --data "5672" http://consul:8500/v1/kv/config/billing-service/spring.rabbitmq.port;
        curl --request PUT --data "guest" http://consul:8500/v1/kv/config/billing-service/spring.rabbitmq.username;
        curl --request PUT --data "guest" http://consul:8500/v1/kv/config/billing-service/spring.rabbitmq.password;
        echo "Configuration loaded successfully into Consul.";
        sleep 10;
  # ----------------------------------------------------
  # Billing Service
  # ----------------------------------------------------
  billing-service:
      image: docker.io/boughroudi/billing-service:latest
      container_name: billing-service
      platform: linux/amd64
      restart: on-failure
      environment:
        - SPRING_RABBITMQ_HOST=rabbitmq
        - SPRING_RABBITMQ_PORT=5672
        - SPRING_RABBITMQ_USERNAME=guest
        - SPRING_RABBITMQ_PASSWORD=guest
      ports:
        - "8086:8080"
      depends_on:
        - config-server
        - consul
        - rabbitmq
      networks:
        - my-network

  # ----------------------------------------------------
  # Scheduling Service
  # ----------------------------------------------------
  scheduling-service:
      image: docker.io/boughroudi/scheduling-service:latest
      container_name: scheduling-service
      platform: linux/amd64
      restart: on-failure
      depends_on:
        - config-server
        - consul
        - rabbitmq
      networks:
        - my-network
      ports:
        - "8083:8080"

  # ----------------------------------------------------
  # Kidney Stone Service (Python)
  # ----------------------------------------------------
  kidney-stone-service:
    image: docker.io/boughroudi/kidney-stone-service:latest
    container_name: kidney-stone-service
    platform: linux/amd64  # Force x86 emulation
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - mongo-db
      - config-server
      - rabbitmq
      - patient-management-service
    networks:
      - my-network
    ports:
      - "8000:8000"

  # ----------------------------------------------------
  # API Gateway Service
  # ----------------------------------------------------
  gateway-service:
      image: docker.io/boughroudi/gateway-service:latest
      container_name: gateway-service
      platform: linux/amd64
      restart: on-failure
      ports:
        - "9999:8080"
      depends_on:
        - config-server
      networks:
        - my-network
  # ----------------------------------------------------
  # Notification Service
  # ----------------------------------------------------
  notification-service:
    image: docker.io/boughroudi/notification-service:latest
    container_name: notification-service
    platform: linux/amd64
    restart: on-failure
    depends_on:
      - config-server
      - consul
      - rabbitmq
    networks:
      - my-network
    ports:
      - "8081:8081"


# --------------------------------------------------------
# Docker Networks & Volumes
# --------------------------------------------------------
networks:
  my-network:
    driver: bridge
