version: "3.8"

services:
  # ----------------------------------------------------
  # Consul
  # ----------------------------------------------------
  consul:
    image: consul:1.15
    container_name: consul
    platform: linux/amd64
    restart: on-failure
    ports:
      - "8500:8500"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 10s
      retries: 5

  # ----------------------------------------------------
  # Config Server
  # ----------------------------------------------------
  config-server:
      image: docker.io/boughroudi/config-server:latest
      container_name: config-server
      platform: linux/amd64
      restart: on-failure
      ports:
        - "8888:8888"
      networks:
        - my-network
      depends_on:
        - consul

  # ----------------------------------------------------
  # RabbitMQ
  # ----------------------------------------------------
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------
  # MongoDB (for kidney-stone-service)
  # ----------------------------------------------------
  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    platform: linux/amd64
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - my-network

  # ----------------------------------------------------
  # Patient Management Service
  # ----------------------------------------------------
  patient-management-service:
      image: docker.io/boughroudi/patient-management-service:latest
      container_name: patient-management-service
      platform: linux/amd64
      restart: on-failure
      ports:
        - "8082:8080"
      depends_on:
        - config-server
        - consul
      networks:
        - my-network

  # ----------------------------------------------------
  # Billing Service
  # ----------------------------------------------------
  billing-service:
      image: docker.io/boughroudi/billing-service:latest
      container_name: billing-service
      platform: linux/amd64
      restart: on-failure
      ports:
        - "8086:8080"
      depends_on:
        - config-server
        - consul
        - rabbitmq
      networks:
        - my-network

  # ----------------------------------------------------
  # Scheduling Service
  # ----------------------------------------------------
  scheduling-service:
      image: docker.io/boughroudi/scheduling-service:latest
      container_name: scheduling-service
      platform: linux/amd64
      restart: on-failure
      depends_on:
        - config-server
        - consul
        - rabbitmq
      networks:
        - my-network
      ports:
        - "8083:8080"

  # ----------------------------------------------------
  # Kidney Stone Service (Python)
  # ----------------------------------------------------
  kidney-stone-service:
    image: docker.io/boughroudi/kidney-stone-service:latest
    container_name: kidney-stone-service
    platform: linux/amd64  # Force x86 emulation
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - mongo-db
      - config-server
      - rabbitmq
      - patient-management-service
    networks:
      - my-network
    ports:
      - "8000:8000"

  # ----------------------------------------------------
  # API Gateway Service
  # ----------------------------------------------------
  gateway-service:
      image: docker.io/boughroudi/gateway-service:latest
      container_name: gateway-service
      platform: linux/amd64
      restart: on-failure
      ports:
        - "9999:8080"
      depends_on:
        - config-server
        - kidney-stone-service
        - patient-management-service
      networks:
        - my-network
  # ----------------------------------------------------
  # Notification Service
  # ----------------------------------------------------
  notification-service:
    image: docker.io/boughroudi/notification-service:latest
    container_name: notification-service
    platform: linux/amd64
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:notification_db
      - NOTIFICATION_QUEUE=notifications  # ✅ Ensure the queue name is passed
    depends_on:
      - config-server
      - consul
      - rabbitmq
    networks:
      - my-network
    ports:
      - "8084:8080"


# --------------------------------------------------------
# Docker Networks & Volumes
# --------------------------------------------------------
networks:
  my-network:
    driver: bridge
