name: CI Pipeline for Healthcare Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the healthcare-infra code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Pull the latest images from DockerHub
      - name: Pull Docker Images
        run: docker compose pull

      # Step 4: Start all services using docker-compose
      - name: Start Services
        run: docker compose up -d

      # Step 5: Wait for services to become healthy
      - name: Wait for Services to Start
        run: |
          echo "Waiting for services to become healthy..."
          sleep 200

      # Step 6: Perform health checks on critical services
      - name: Run Health Checks
        run: |
          curl -f http://localhost:8500/v1/status/leader || exit 1      # Consul
          curl -f http://localhost:8888/actuator/health || exit 1      # Config Server
          curl -f http://localhost:8082/actuator/health || exit 1      # Patient Management
          curl -f http://localhost:8086/actuator/health || exit 1      # Billing Service
          curl -f http://localhost:8083/actuator/health || exit 1      # Scheduling Service
          curl -f http://localhost:8000/health || exit 1               # Kidney Stone Service
          curl -f http://localhost:9999/actuator/health || exit 1      # Gateway Service
          echo "All services are healthy!"

      # Step 7: Run integration tests (e.g., Postman or curl-based tests)
      - name: Run Integration Tests
        run: |
          echo "Running integration tests..."
          curl -X POST http://localhost:8082/api/patients -H "Content-Type: application/json" -d '{"name":"John Doe", "age":30}'
          curl -X GET http://localhost:8082/api/patients
          curl -X POST http://localhost:8083/api/appointments -H "Content-Type: application/json" -d '{"patientId":1, "date":"2025-02-06"}'
          echo "Integration tests passed!"

      # Step 8: Shut down the services
      - name: Shut Down Services
        if: always()
        run: docker compose down
